config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :conference_subthemes
  resources :conference_themes
  resources :comments
  resources :papers do
    collection do
      get :conference_subthemes
    end
  end

  root :to => 'home#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/conference_subtheme.rb
class ConferenceSubtheme < ApplicationRecord
  belongs_to :conference_theme

end

app/controllers/conference_subthemes_controller.rb
class ConferenceSubthemesController < ApplicationController
  before_action :set_conference_subtheme, only: %i[ show edit update destroy ]

  # GET /conference_subthemes or /conference_subthemes.json
  def index
    @conference_subthemes = ConferenceSubtheme.all
  end

  # GET /conference_subthemes/1 or /conference_subthemes/1.json
  def show
  end

  # GET /conference_subthemes/new
  def new
    @conference_subtheme = ConferenceSubtheme.new
  end

  # GET /conference_subthemes/1/edit
  def edit
  end

  # POST /conference_subthemes or /conference_subthemes.json
  def create
    @conference_subtheme = ConferenceSubtheme.new(conference_subtheme_params)

    respond_to do |format|
      if @conference_subtheme.save
        format.html { redirect_to conference_subtheme_url(@conference_subtheme), notice: "Conference subtheme was successfully created." }
        format.json { render :show, status: :created, location: @conference_subtheme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conference_subtheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conference_subthemes/1 or /conference_subthemes/1.json
  def update
    respond_to do |format|
      if @conference_subtheme.update(conference_subtheme_params)
        format.html { redirect_to conference_subtheme_url(@conference_subtheme), notice: "Conference subtheme was successfully updated." }
        format.json { render :show, status: :ok, location: @conference_subtheme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conference_subtheme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conference_subthemes/1 or /conference_subthemes/1.json
  def destroy
    @conference_subtheme.destroy

    respond_to do |format|
      format.html { redirect_to conference_subthemes_url, notice: "Conference subtheme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference_subtheme
      @conference_subtheme = ConferenceSubtheme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def conference_subtheme_params
      params.require(:conference_subtheme).permit(:name, :conference_theme_id)
    end
end

app/helpers/conference_subthemes_helper.rb
module ConferenceSubthemesHelper
end

app/views/conference_subthemes/_form.html.erb
<%= form_with(model: conference_subtheme) do |form| %>
  <% if conference_subtheme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conference_subtheme.errors.count, "error") %> prohibited this conference_subtheme from being saved:</h2>

      <ul>
        <% conference_subtheme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :conference_theme_id %>
    <%= form.select :conference_theme_id, options_from_collection_for_select(ConferenceTheme.all, 'id', 'name') %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conference_subthemes/edit.html.erb
<h1>Editing Conference Subtheme</h1>

<%= render 'form', conference_subtheme: @conference_subtheme %>

<%= link_to 'Show', @conference_subtheme %> |
<%= link_to 'Back', conference_subthemes_path %>

app/views/conference_subthemes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conference Subthemes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Conference theme</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conference_subthemes.each do |conference_subtheme| %>
      <tr>
        <td><%= conference_subtheme.name %></td>
        <td><%= conference_subtheme.conference_theme.name %></td>
        <td><%= link_to 'Show', conference_subtheme %></td>
        <td><%= link_to 'Edit', edit_conference_subtheme_path(conference_subtheme) %></td>
        <td><%= link_to 'Destroy', conference_subtheme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conference Subtheme', new_conference_subtheme_path %>

app/views/conference_subthemes/new.html.erb
<h1>New Conference Subtheme</h1>

<%= render 'form', conference_subtheme: @conference_subtheme %>

<%= link_to 'Back', conference_subthemes_path %>

app/views/conference_subthemes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @conference_subtheme.name %>
</p>

<p>
  <strong>Conference theme:</strong>
  <%= @conference_subtheme.conference_theme.name%>
</p>

<%= link_to 'Edit', edit_conference_subtheme_path(@conference_subtheme) %> |
<%= link_to 'Back', conference_subthemes_path %>