config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :conference_subthemes
  resources :conference_themes
  resources :comments
  resources :papers do
    collection do
      get :conference_subthemes
    end
  end

  root :to => 'home#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/paper.rb
class Paper < ApplicationRecord
 belongs_to :conference_theme
 belongs_to :conference_subtheme

 has_rich_text :content
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: %i[ show edit update destroy ]

  # GET /papers or /papers.json
  def index
    @papers = Paper.all
  end

  # GET /papers/1 or /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end

  # POST /papers or /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to paper_url(@paper), notice: "Paper was successfully created." }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1 or /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to paper_url(@paper), notice: "Paper was successfully updated." }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1 or /papers/1.json
  def destroy
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to papers_url, notice: "Paper was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def conference_subthemes
    @target = params[:target]
    @conference_theme = ConferenceTheme.find(params[:conference_theme_id])
    @conference_subthemes = ConferenceSubtheme.where(conference_theme: @conference_theme)

    respond_to do |format|
      format.turbo_stream
      format.json {head :no_content}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paper_params
      params.require(:paper).permit(:title, :conference_theme_id, :conference_subtheme_id, :content, :status)
    end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.erb
<%= form_with(model: paper, local: true) do |form| %>
  <% if paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
        <% paper.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div data-controller="subthemes" >
    <div class="field" >
      <%= form.label :conference_theme_id %>
      <%= form.select :conference_theme_id, options_from_collection_for_select(ConferenceTheme.all, 'id', 'name'), {prompt: "Select a theme"}, {class: 'form-select', data: {action: "change->subthemes#change"}}%>
    </div>

    <div class="field">
      <%= form.label :conference_subtheme_id %>
      <%= form.select :conference_subtheme_id, (form.object.conference_theme_id? ? debug(ConferenceTheme.find(form.object.conference_theme_id)) : []), {}, { class: 'form-select', data: { subthemes_target: "select" } }%>
    </div>

  </div>
  
  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="field">
    <%= form.number_field :status, {value:1, hidden:true}%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/papers/conference_subthemes.turbo_stream.erb
<%= turbo_stream.update @target do %>
    
    <%= options_from_collection_for_select(ConferenceSubtheme.where(conference_theme: @conference_theme), 'id', 'name') %>
<% end %>

app/views/papers/edit.html.erb
<h1>Editing Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

app/views/papers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Papers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Theme</th>
      <th>Subtheme</th>
      <th>Content</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.title %></td>
        <td><%= paper.conference_theme.name %></td>
        <td><%= paper.conference_subtheme.name %></td>
        <td><%= paper.status %></td>
        <td><%= link_to 'Show', paper %></td>
        <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
        <td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paper', new_paper_path %>

app/views/papers/new.html.erb
<h1>New Paper</h1>

<%= render 'form', paper: @paper %>

<%= link_to 'Back', papers_path %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @paper.title %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @paper.conference_theme_id %>
</p>

<p>
  <strong>Subtheme:</strong>
  <%= @paper.conference_subtheme_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @paper.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @paper.status %>
</p>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>