config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :conference_subthemes
  resources :conference_themes
  resources :comments
  resources :papers do
    collection do
      get :conference_subthemes
    end
  end

  root :to => 'home#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/conference_theme.rb
class ConferenceTheme < ApplicationRecord
    has_many :conference_subtheme
end

app/controllers/conference_themes_controller.rb
class ConferenceThemesController < ApplicationController
  before_action :set_conference_theme, only: %i[ show edit update destroy ]

  # GET /conference_themes or /conference_themes.json
  def index
    @conference_themes = ConferenceTheme.all
  end

  # GET /conference_themes/1 or /conference_themes/1.json
  def show
    @conference_subthemes = @conference_theme.conference_subtheme
  end

  # GET /conference_themes/new
  def new
    @conference_theme = ConferenceTheme.new
  end

  # GET /conference_themes/1/edit
  def edit
  end

  # POST /conference_themes or /conference_themes.json
  def create
    @conference_theme = ConferenceTheme.new(conference_theme_params)

    respond_to do |format|
      if @conference_theme.save
        format.html { redirect_to conference_theme_url(@conference_theme), notice: "Conference theme was successfully created." }
        format.json { render :show, status: :created, location: @conference_theme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conference_theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conference_themes/1 or /conference_themes/1.json
  def update
    respond_to do |format|
      if @conference_theme.update(conference_theme_params)
        format.html { redirect_to conference_theme_url(@conference_theme), notice: "Conference theme was successfully updated." }
        format.json { render :show, status: :ok, location: @conference_theme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conference_theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conference_themes/1 or /conference_themes/1.json
  def destroy
    @conference_theme.destroy

    respond_to do |format|
      format.html { redirect_to conference_themes_url, notice: "Conference theme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference_theme
      @conference_theme = ConferenceTheme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def conference_theme_params
      params.require(:conference_theme).permit(:name)
    end
end

app/helpers/conference_themes_helper.rb
module ConferenceThemesHelper
end

app/views/conference_themes/_form.html.erb
<%= form_with(model: conference_theme) do |form| %>
  <% if conference_theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(conference_theme.errors.count, "error") %> prohibited this conference_theme from being saved:</h2>

      <ul>
        <% conference_theme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/conference_themes/edit.html.erb
<h1>Editing Conference Theme</h1>

<%= render 'form', conference_theme: @conference_theme %>

<%= link_to 'Show', @conference_theme %> |
<%= link_to 'Back', conference_themes_path %>

app/views/conference_themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conference Themes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conference_themes.each do |conference_theme| %>
      <tr>
        <td><%= conference_theme.name %></td>
        <td><%= link_to 'Show', conference_theme %></td>
        <td><%= link_to 'Edit', edit_conference_theme_path(conference_theme) %></td>
        <td><%= link_to 'Destroy', conference_theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conference Theme', new_conference_theme_path %>

app/views/conference_themes/new.html.erb
<h1>New Conference Theme</h1>

<%= render 'form', conference_theme: @conference_theme %>

<%= link_to 'Back', conference_themes_path %>

app/views/conference_themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @conference_theme.name %>
</p>

<h1>Subthemes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @conference_subthemes.each do |conference_subtheme| %>
      <tr>
        <td><%= conference_subtheme.name %></td>
        <td><%= link_to 'Show', conference_subtheme %></td>
        <td><%= link_to 'Edit', edit_conference_subtheme_path(conference_subtheme) %></td>
        <td><%= link_to 'Destroy', conference_subtheme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Edit', edit_conference_theme_path(@conference_theme) %> |
<%= link_to 'Back', conference_themes_path %>